import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const app = new URL("../app/", import.meta.url);

test("统一面板由后端模型目录驱动并提供完整分析工作视图", async () => {
  const source = await readFile(new URL("Dashboard.tsx", app), "utf8");
  assert.match(source, /\/api\/models/);
  assert.match(source, /\/api\/analytics/);
  assert.match(source, /模型总览/);
  assert.match(source, /问题对比/);
  assert.match(source, /信源洞察/);
  assert.match(source, /品牌与产品/);
  assert.match(source, /回答审计/);
  assert.match(source, /采集控制/);
  assert.doesNotMatch(source, /modelRegistry/);
  assert.match(source, /const visibleModelCatalog = analytics\.model_catalog/);
  assert.match(source, /\(item\) => !model \|\| item\.id === model/);
  assert.doesNotMatch(source, /item\.ingest_only \|\| item\.id === model \|\| item\.runs > 0/);
  assert.match(source, /const participatingModelCount = selectedModels\.filter/);
  assert.match(source, /有数据模型 \/ 设备/);
});

test("采集控制包含问题计划、账号校验及启停能力", async () => {
  const source = await readFile(new URL("Dashboard.tsx", app), "utf8");
  assert.match(source, /每行一个，启动前自动保存/);
  assert.match(source, /仅保存问题/);
  assert.match(source, /检查网页登录/);
  assert.match(source, /account-check/);
  assert.match(source, /api\/control\/\$\{modelId\}/);
  assert.doesNotMatch(source, /实时回传日志/);
  assert.match(source, /启动请求已接收/);
  assert.match(source, /正在启动…/);
  assert.match(source, /Chrome 启动、账号校验完成后会自动运行采集脚本/);
  assert.match(source, /状态每 2 秒从采集日志同步/);
  assert.match(source, /无头网页直采/);
  assert.match(source, /打开远程任务中心/);
  assert.match(source, /window\.location\.port === "3000"/);
  assert.match(source, /Production Nginx exposes the frontend and \/api on one HTTPS origin/);
});

test("信源分析区显示每日 Top 25、关键词和五模型自有链接交集", async () => {
  const source = await readFile(new URL("Dashboard.tsx", app), "utf8");
  assert.match(source, /高频文章 Top 25/);
  assert.match(source, /高频视频 Top 25/);
  assert.match(source, /文章文案关键词/);
  assert.match(source, /视频文案关键词/);
  assert.match(source, /自有品牌/);
  assert.match(source, /文章标题关键词每日变化/);
  assert.match(source, /正文产品提及率与每日名次/);
  assert.match(source, /不等待产品 AI 解析/);
  assert.match(source, /待解析不计为未提及/);
  assert.match(source, /个已分析唯一信源提及/);
  assert.match(source, /个待正文分析/);
  assert.match(source, /五模型共同提取的自有信源链接/);
  assert.match(source, /未同时被五个模型提取的链接不会显示/);
  assert.match(source, /恰好被两个模型共同提取的自有信源链接/);
  assert.match(source, /已进入五模型交集的链接不重复展示/);
  assert.match(source, /选择对象/);
  assert.match(source, /竞品（文章正文命中）/);
  assert.match(source, /高\/中质量文章正文/);
  assert.match(source, /严格服从当前问题和日期口径/);
  assert.match(source, /common_competitor_sources/);
  assert.match(source, /two_model_competitor_sources/);
  assert.match(source, /全部非自有竞品/);
  assert.match(source, /allCompetitors/);
  assert.match(source, /api\/analytics\/source-intersections/);
  assert.match(source, /模型交集均按当前全部日期完整统计/);
  assert.match(source, /sourceIntersectionsMatch/);
});

test("总览提供每日自有产品跨模型上榜看板并区分缺数与负样本", async () => {
  const source = await readFile(new URL("Dashboard.tsx", app), "utf8");
  assert.match(source, /我的产品每日上榜情况/);
  assert.match(source, /任意1轮回答正文确认推荐，即记为上榜/);
  assert.match(source, /已上榜/);
  assert.match(source, /未上榜/);
  assert.match(source, /待复核/);
  assert.match(source, /未采集/);
  assert.match(source, /owned_product_daily/);
  assert.match(source, /models\.map\(\(item\) => <th key=\{item\.id\}>\{item\.name\}<\/th>\)/);
  assert.match(source, /const display = stateText\(row\.models\[item\.id\]\)/);
});

test("页面元数据使用企业级 GEO 产品名称", async () => {
  const layout = await readFile(new URL("layout.tsx", app), "utf8");
  assert.match(layout, /GEO Monitor · AI 品牌推荐诊断/);
  assert.match(layout, /持续监测平台/);
  assert.doesNotMatch(layout, /Starter Project|codex-preview|豆包 × 元宝/);
});

test("客户从根页面创建诊断并在完成后进入随机密钥报告页", async () => {
  const home = await readFile(new URL("page.tsx", app), "utf8");
  const start = await readFile(new URL("DiagnosisStart.tsx", app), "utf8");
  const login = await readFile(new URL("DiagnosisAdmin.tsx", app), "utf8");
  const icons = await readFile(new URL("ModelIcon.tsx", app), "utf8");
  const styles = await readFile(new URL("globals.css", app), "utf8");
  const source = await readFile(new URL("DiagnosisDashboard.tsx", app), "utf8");
  const route = await readFile(new URL("[customer]/page.tsx", app), "utf8");
  const missingRoute = await readFile(new URL("[customer]/[...missing]/page.tsx", app), "utf8");
  const admin = await readFile(new URL("admin/page.tsx", app), "utf8");
  const authGate = await readFile(new URL("SiteAuthGate.tsx", app), "utf8");
  assert.match(styles, /GEO Monitor interface system/);
  assert.match(styles, /--font-ui:/);
  assert.match(styles, /--radius-lg: 20px/);
  assert.match(styles, /--shadow-md:/);
  assert.match(home, /DiagnosisStart/);
  assert.doesNotMatch(home, /<Dashboard/);
  assert.match(start, /\/api\/diagnosis/);
  assert.match(start, /report_key/);
  assert.match(start, /geoActiveReportKey/);
  assert.match(start, /response\.status === 404/);
  assert.match(start, /clearActiveDiagnosis/);
  assert.match(start, /sessionStorage\.removeItem\("geoActiveReportKey"\)/);
  assert.match(start, /window\.location\.pathname\.startsWith\("\/geo\/"\)/);
  assert.match(start, /采集服务连接失败，正在自动重试/);
  assert.match(start, /window\.location\.assign/);
  assert.match(start, /诊断产品/);
  assert.match(start, /提交诊断/);
  assert.match(start, /EnterpriseBrandLockup/);
  assert.match(start, /diagnosis-workspace/);
  assert.match(start, /多平台抽样/);
  assert.doesNotMatch(start, /总提问轮次/);
  assert.doesNotMatch(start, /常规模型\/DeepSeek/);
  assert.match(start, /DeepSeek/);
  assert.match(start, /Kimi/);
  assert.match(start, /当前任务执行中/);
  assert.match(start, /当前任务排队中/);
  assert.match(login, /id: "deepseek"/);
  assert.match(login, /id: "kimi"/);
  assert.match(login, /id: "quark", name: "千问"/);
  assert.match(login, /公开访问/);
  assert.match(login, /截止时间（留空为永久）/);
  assert.match(login, /api\/admin\/reports\/\$\{item\.report_key\}\/sharing/);
  assert.match(login, /api\/admin\/reports\/\$\{deleteCandidate\.report_key\}\/delete/);
  assert.match(login, /确认永久删除/);
  assert.match(login, /confirm_brand/);
  assert.match(login, /api\/admin\/reports\/\$\{item\.report_key\}\/editor/);
  assert.match(login, /api\/admin\/reports\/\$\{reportEditor\.report_key\}\/edit/);
  assert.match(login, /api\/admin\/reports\/\$\{reportKey\}\/revert/);
  assert.match(login, /编辑报告/);
  assert.match(login, /保存并重新计算报告/);
  assert.match(login, /撤回所有修改/);
  assert.match(login, /manual_edit_count/);
  assert.match(login, /session\?\.role === "super_admin" && item\.report_key/);
  assert.match(login, /ReportRecordForm/);
  assert.match(login, /回答正文/);
  assert.match(login, /产品与排名/);
  assert.match(login, /引用信源/);
  assert.match(login, /展开编辑/);
  assert.match(login, /admin-record-toggle/);
  assert.doesNotMatch(login, /报告采集数据（JSON）/);
  assert.match(login, /搜索品牌、产品或诊断问题/);
  assert.match(login, /复制公开链接/);
  assert.match(styles, /admin-report-toolbar/);
  assert.match(styles, /admin-delete-dialog/);
  assert.match(styles, /admin-report-editor/);
  assert.match(styles, /admin-record-form/);
  assert.match(styles, /admin-revert-report/);
  assert.match(login, /暂停公开/);
  assert.match(login, /开启公开/);
  assert.match(login, /已到期/);
  assert.match(login, /EnterpriseBrandLockup/);
  assert.match(login, /EnterpriseBrandMark/);
  assert.match(login, /下级管理员账号/);
  assert.match(login, /api\/admin\/accounts/);
  assert.match(login, /每日最多诊断/);
  assert.match(login, /暂停账号/);
  assert.match(login, /重置今日次数/);
  assert.match(login, /api\/admin\/accounts\/\$\{accountId\}\/reset-quota/);
  assert.match(login, /created_by_username/);
  assert.match(login, /session\?\.role === "super_admin"/);
  assert.match(start, /今日额度已用完/);
  assert.match(start, /next\.quota/);
  assert.match(icons, /fill="#2388FF"/);
  assert.match(icons, /fill="#050505"/);
  assert.match(icons, /tone === "quark" \|\| tone === "qwen" \? QwenIcon/);
  assert.match(styles, /prefers-reduced-motion:reduce/);
  assert.match(styles, /animation-duration:72s/);
  assert.match(styles, /Readable customer report: larger type, roomier data cards and true mobile flow/);
  assert.match(styles, /diagnosis-shell-report \.diagnosis-report-grid dt/);
  assert.match(styles, /@media \(max-width: 560px\)/);
  assert.match(styles, /overflow-wrap: anywhere/);
  assert.match(start, /重新运行本次诊断/);
  assert.match(start, /返回重新填写/);
  assert.match(start, /retryFailedTask/);
  assert.match(start, /diagnosis-customer-steps/);
  assert.match(start, /ahead_if_submitted/);
  assert.match(start, /当前排队位置/);
  assert.match(start, /系统每 3 秒更新位置/);
  assert.doesNotMatch(start, /task\?\.events\?\.slice/);
  assert.match(source, /六大 AI 平台 · 独立会话采集/);
  assert.match(source, /diagnosis-shell-\$\{tab\}/);
  assert.doesNotMatch(source, /DeepSeek\/Kimi 2 轮/);
  assert.match(source, /平均可见度/);
  assert.match(source, /首推占比/);
  assert.match(source, /diagnosis-metric-icon/);
  assert.match(source, /小样本置信校准/);
  assert.match(source, /推荐名次加权/);
  assert.doesNotMatch(source, /未提及品牌|仅提及品牌/);
  assert.doesNotMatch(source, /<span className=\{answer\.recommended \? "hit"/);
  assert.match(source, /answerParagraphs/);
  assert.doesNotMatch(source, /20–30 点稳定折减/);
  assert.match(source, /diagnosis-model-probability-grid/);
  assert.match(source, /校准评分 · 原始命中/);
  assert.doesNotMatch(source, /代采参考|Kimi 代采不参与总体计权|使用 DeepSeek 样本/);
  assert.doesNotMatch(source, /当前采用高概率策略|当前采用普通品牌策略/);
  assert.match(login, /高概率品牌名单/);
  assert.match(login, /high_probability_brands/);
  assert.match(login, /当前采用高概率策略/);
  assert.match(login, /当前采用普通品牌策略/);
  assert.match(source, /竞争格局/);
  assert.match(source, /竞争可见度/);
  assert.match(source, /competitor\.mention_models \|\| competitor\.models/);
  assert.match(source, /回答中提及厂商，未识别具体产品/);
  assert.match(source, /工艺、设备类型和店铺名称不计作竞品品牌/);
  assert.match(source, /diagnosis-competitor-evidence/);
  assert.match(source, /diagnosis-competitor-scroll/);
  assert.match(source, /列表区域可上下滑动/);
  assert.match(source, /AI 平台维度详情/);
  assert.ok(source.indexOf("diagnosis-model-probability-grid") < source.indexOf("AI 平台维度详情"));
  assert.ok(source.indexOf("AI 平台维度详情") < source.indexOf("竞争格局"));
  assert.match(source, /id="diagnosis-evidence-card"/);
  assert.match(source, /抽样回答与信源/);
  assert.match(source, /展开全部样本/);
  assert.match(source, /抽样记录/);
  assert.match(source, /抽样展示结束/);
  assert.match(source, /本次抽样回答信源/);
  assert.match(source, /EnterpriseBrandMark/);
  assert.doesNotMatch(source, /<button onClick=\{showEvidence\}>回答与信源<\/button>/);
  assert.doesNotMatch(source, /样本 n=/);
  assert.doesNotMatch(source, /明确推荐次数/);
  assert.doesNotMatch(source, /report\.sources\.slice\(0, 30\)/);
  assert.doesNotMatch(source, /实时诊断日志/);
  assert.match(source, /api\/diagnosis\/\$\{customerSlug\}/);
  assert.match(source, /response\.status === 404/);
  assert.match(source, /!next\.task \|\| next\.task\.status !== "completed"/);
  assert.match(source, /sessionStorage\.removeItem\("geoActiveReportKey"\)/);
  assert.match(source, /window\.location\.replace/);
  assert.doesNotMatch(source, /startDiagnosis/);
  assert.match(route, /DiagnosisDashboard/);
  assert.match(route, /\^\[a-f0-9\]\{32\}\$/);
  assert.match(route, /redirect\(rootPath\)/);
  assert.match(route, /MONITOR_PUBLIC_ORIGIN/);
  assert.match(route, /api\/diagnosis\/\$\{reportKey\}/);
  assert.match(route, /requestHeaders\.get\("cookie"\)/);
  assert.match(route, /payload\?\.task\?\.status !== "completed"/);
  assert.match(route, /dynamic = "force-dynamic"/);
  assert.match(route, /revalidate = 0/);
  assert.match(missingRoute, /redirect\(/);
  assert.match(missingRoute, /MONITOR_PUBLIC_ORIGIN/);
  assert.match(admin, /Dashboard/);
  assert.match(authGate, /isPublicCompletedReportPath/);
  assert.match(authGate, /\[a-f0-9\]\{32\}/);
  assert.match(authGate, /api\/admin\/session/);
  assert.match(authGate, /window\.location\.replace/);
  assert.match(authGate, /AUTH_CHECK_TIMEOUT_MS = 5000/);
  assert.match(authGate, /AbortController/);
  assert.match(authGate, /signal: controller\.signal/);
  assert.match(authGate, /立即前往登录/);
});

test("总管理员无限额度不会被 remaining=0 误判为无额度", async () => {
  const source = await readFile(new URL("DiagnosisStart.tsx", app), "utf8");
  assert.match(source, /quota\?\.limited === true && quota\.remaining === 0/);
  assert.doesNotMatch(source, /disabled=\{submitting \|\| quota\?\.remaining === 0/);
});

test("生产构建默认把前端资源挂载在 /geo 下", async () => {
  const config = await readFile(new URL("../vite.config.ts", import.meta.url), "utf8");
  const packageJson = await readFile(new URL("../package.json", import.meta.url), "utf8");
  const verifier = await readFile(new URL("../scripts/verify-production-assets.mjs", import.meta.url), "utf8");
  assert.match(config, /process\.env\.NODE_ENV === "production" \? "\/geo"/);
  assert.match(config, /configuredBasePath\.replace/);
  assert.match(packageJson, /verify:production-assets/);
  assert.match(verifier, /refusing to publish an unstyled dashboard/);
  assert.match(verifier, /Production CSS or JavaScript assets are missing/);
});

test("日期筛选首屏按北京时间一次性初始化", async () => {
  const source = await readFile(new URL("Dashboard.tsx", app), "utf8");
  assert.match(source, /const \[date, setDate\] = useState\(\(\) => new Intl\.DateTimeFormat/);
  assert.doesNotMatch(source, /localStorage\.getItem\("monitorSelectedDate"\)/);
  assert.match(source, /localStorage\.setItem\("monitorSelectedDate", date\)/);
  assert.match(source, /timeZone: "Asia\/Shanghai"/);
  assert.match(source, /const filtersReady = true/);
  assert.match(source, /if \(!filtersReady\) return/);
  assert.doesNotMatch(source, /setFiltersReady/);
});

test("分析刷新不做日期预取并使用低开销条件轮询", async () => {
  const source = await readFile(new URL("Dashboard.tsx", app), "utf8");
  assert.doesNotMatch(source, /analyticsPrefetches|datesToWarm/);
  assert.doesNotMatch(source, /targetView of \["brands", "compare", "sources"\]/);
  assert.match(source, /silent && analyticsRequest\.current/);
  assert.match(source, /setInterval\(refreshLiveData, 15000\)/);
  assert.match(source, /analyticsResponseEtag/);
  assert.match(source, /cache: "no-cache"/);
  assert.match(source, /A filter label must never be paired with the previous filter's rows/);
  assert.doesNotMatch(source, /analyticsPayload\.questions\.includes\(question\).*setQuestion/);
  assert.doesNotMatch(source, /analyticsPayload\.dates\.includes\(date\).*setDate/);
  assert.match(source, /selectors must remain controlled by the user's last action/);
  assert.match(source, /filters\?\.view \|\| ""/);
  assert.match(source, /全部日期汇总已加载/);
  assert.match(source, /全部日期完整统计/);
  assert.match(source, /if \(view === "control"\)/);
  assert.match(source, /view !== "control" && \(/);
});

test("总管理员可配置并实时控制付费用户每日监控", async () => {
  const admin = await readFile(new URL("DiagnosisAdmin.tsx", app), "utf8");
  const monitor = await readFile(new URL("PaidMonitorCenter.tsx", app), "utf8");
  const monitorRoute = await readFile(new URL("admin/paid-monitors/page.tsx", app), "utf8");
  assert.match(admin, /付费用户每日监控/);
  assert.match(admin, /PaidMonitorCenter/);
  assert.match(admin, /initialView = "reports"/);
  assert.match(admin, /admin\/paid-monitors/);
  assert.match(admin, /isPaidMonitorPage && session\?\.role === "super_admin" && <PaidMonitorCenter/);
  assert.match(monitorRoute, /initialView="paid-monitors"/);
  assert.match(monitor, /api\/admin\/paid-monitors/);
  assert.match(monitor, /setInterval\(.*3000/);
  for (const action of ["pause", "resume", "rerun", "clear"]) assert.match(monitor, new RegExp(action));
  for (const model of ["doubao", "yuanbao", "wenxin", "quark", "deepseek", "kimi"]) assert.match(monitor, new RegExp(model));
});

test("付费用户使用独立的百一电子式每日趋势面板", async () => {
  const dashboard = await readFile(new URL("PaidCustomerDashboard.tsx", app), "utf8");
  const customerRoute = await readFile(new URL("[customer]/page.tsx", app), "utf8");
  const gate = await readFile(new URL("SiteAuthGate.tsx", app), "utf8");
  for (const section of ["监测概览", "概率趋势", "竞品分析", "信源追踪"]) {
    assert.match(dashboard, new RegExp(section));
  }
  assert.match(dashboard, /api\/paid-monitor/);
  assert.match(customerRoute, /PaidCustomerDashboard/);
  assert.match(customerRoute, /paid-\[a-f0-9\]\{24\}/);
  assert.match(gate, /paid-\[a-f0-9\]\{24\}/);
});

test("诊断报告深色横幅标题保持高对比可读", async () => {
  const styles = await readFile(new URL("globals.css", app), "utf8");
  assert.match(styles, /\.diagnosis-hero h2,\.report-hero h2\s*\{\s*color:#f8fbff!important;/);
  assert.match(styles, /\.diagnosis-hero p,\.report-hero p\s*\{\s*color:#c5d0e0!important;/);
});
